; PlatformIO Project Configuration File

[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

board_build.filesystem = littlefs

monitor_speed = 115200
monitor_filters =
  esp32_exception_decoder

test_build_src = true

lib_ignore =
  ESPAsyncTCP
  AsyncTCP_RP2040W

build_unflags =
  -std=gnu++11

build_flags =
  -std=gnu++20
  -I../../.deps/rapidjson/include
  -I../../.deps/lodepng
  -I../../.deps/tjpgd
  -I../../.deps/yoga

lib_deps =
  multigauge-yoga
  multigauge-lodepng
  multigauge-tjpgd

extra_scripts =
  pre:bootstrap-deps.py