from .admin import admin_bp
from .auth import auth_bp
from .cart import cart_bp
from .main import main_bp
from .multigauge_web import multigauge_web_bp
from .account import account_bp
from .payment import payment_bp
from .products import products_bp
from .subscribers import subscribers_bp
from .users import users_bp
from .workshop import workshop_bp
