if(DEFINED MULTIGAUGE_DEPENDENCIES_INCLUDED)
  return()
endif()
set(MULTIGAUGE_DEPENDENCIES_INCLUDED TRUE)

if(NOT DEFINED MULTIGAUGE_DEPS_DIR)
  set(MULTIGAUGE_DEPS_DIR "${CMAKE_CURRENT_LIST_DIR}/../.deps")
endif()

set(MULTIGAUGE_DEP_RAPIDJSON_URL "https://github.com/Tencent/rapidjson.git")
set(MULTIGAUGE_DEP_RAPIDJSON_TAG "v1.1.0")
set(MULTIGAUGE_DEP_RAPIDJSON_DIR "${MULTIGAUGE_DEPS_DIR}/rapidjson")

set(MULTIGAUGE_DEP_YOGA_URL "https://github.com/facebook/yoga.git")
set(MULTIGAUGE_DEP_YOGA_TAG "v2.0.0")
set(MULTIGAUGE_DEP_YOGA_DIR "${MULTIGAUGE_DEPS_DIR}/yoga")

set(MULTIGAUGE_DEP_LODEPNG_DIR "${MULTIGAUGE_DEPS_DIR}/lodepng")
set(MULTIGAUGE_DEP_LODEPNG_CPP_URL "https://raw.githubusercontent.com/lvandeve/lodepng/master/lodepng.cpp")
set(MULTIGAUGE_DEP_LODEPNG_H_URL "https://raw.githubusercontent.com/lvandeve/lodepng/master/lodepng.h")

set(MULTIGAUGE_DEP_TJPGD_DIR "${MULTIGAUGE_DEPS_DIR}/tjpgd")
set(MULTIGAUGE_DEP_TJPGD_C_URL "https://raw.githubusercontent.com/cmumford/TJpgDec/master/src/tjpgd.c")
set(MULTIGAUGE_DEP_TJPGD_H_URL "https://raw.githubusercontent.com/cmumford/TJpgDec/master/src/tjpgd.h")
set(MULTIGAUGE_DEP_TJPGD_CONFIG_URL "https://raw.githubusercontent.com/cmumford/TJpgDec/master/src/tjpgdcnf.h")

function(multigauge_download_file url destination)
  if(EXISTS "${destination}")
    return()
  endif()

  get_filename_component(destination_dir "${destination}" DIRECTORY)
  file(MAKE_DIRECTORY "${destination_dir}")
  file(DOWNLOAD "${url}" "${destination}" STATUS download_status TLS_VERIFY ON)
  list(GET download_status 0 download_code)
  list(GET download_status 1 download_message)
  if(NOT download_code EQUAL 0)
    message(FATAL_ERROR "Failed to download ${url}: ${download_message}")
  endif()
endfunction()

function(multigauge_clone_repo url tag destination)
  if(EXISTS "${destination}/.git" OR EXISTS "${destination}/.multigauge-ready")
    return()
  endif()
  if(EXISTS "${destination}")
    message(FATAL_ERROR "Dependency directory exists but is incomplete: ${destination}")
  endif()

  get_filename_component(destination_parent "${destination}" DIRECTORY)
  file(MAKE_DIRECTORY "${destination_parent}")
  execute_process(
    COMMAND git clone --depth 1 --branch "${tag}" "${url}" "${destination}"
    RESULT_VARIABLE clone_result
  )
  if(NOT clone_result EQUAL 0)
    message(FATAL_ERROR "Failed to clone ${url} (${tag})")
  endif()
  file(WRITE "${destination}/.multigauge-ready" "ok\n")
endfunction()

function(multigauge_clone_dependency name)
  set(url_var "MULTIGAUGE_DEP_${name}_URL")
  set(tag_var "MULTIGAUGE_DEP_${name}_TAG")
  set(dir_var "MULTIGAUGE_DEP_${name}_DIR")
  multigauge_clone_repo("${${url_var}}" "${${tag_var}}" "${${dir_var}}")
endfunction()

function(multigauge_patch_rapidjson rapidjson_include_dir)
  set(document_header "${rapidjson_include_dir}/rapidjson/document.h")
  if(NOT EXISTS "${document_header}")
    return()
  endif()

  file(READ "${document_header}" document_content)
  set(broken_assignment "GenericStringRef& operator=(const GenericStringRef& rhs) { s = rhs.s; length = rhs.length; }")
  string(FIND "${document_content}" "${broken_assignment}" broken_assignment_index)
  if(NOT broken_assignment_index EQUAL -1)
    string(REPLACE "${broken_assignment}" "GenericStringRef& operator=(const GenericStringRef& rhs) = delete;" patched_content "${document_content}")
    file(WRITE "${document_header}" "${patched_content}")
  endif()
endfunction()
