name: Core Build

on:
  workflow_call:
    inputs:
      fetch_depth:
        type: number
        default: 1
      build_type:
        type: string
        default: Debug
      build_target:
        type: string
        default: multigauge_ci

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.fetch_depth }}

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.workflow }}-${{ github.job }}-${{ runner.os }}

      - name: Configure
        run: |
          cmake -S . -B build `
            -DCMAKE_C_COMPILER_LAUNCHER=ccache `
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache `
            -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} `
            -DMULTIGAUGE_BUILD_WEB=OFF

      - name: Build
        run: cmake --build build --config ${{ inputs.build_type }} --target ${{ inputs.build_target }} -j $(nproc)

      - name: Test
        run: ctest --test-dir build/core -C ${{ inputs.build_type }} --output-on-failure
