name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  core:
    uses: ./.github/workflows/build-core.yml
    with:
      fetch_depth: 1
      build_type: Debug
      build_target: multigauge_ci

  firmware:
    needs: core
    uses: ./.github/workflows/build-firmware.yml
    with:
      fetch_depth: 1
      upload_artifact: false

  web:
    needs: core
    uses: ./.github/workflows/build-web.yml
    with:
      fetch_depth: 1
      build_type: Debug
      upload_artifact: true
