name: Deploy Firmware

on:
  push:
    tags:
      - 'ports-esp32@*'

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build-firmware.yml
    with:
      fetch_depth: 1
      upload_artifact: true

  publish:
    name: Upload ESP32 Firmware to GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Firmware Artifact
        uses: actions/download-artifact@v4
        with:
          name: multigauge-firmware
          path: firmware-artifact

      - name: Upload Firmware Bin to GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: firmware-artifact/firmware.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
