name: Deploy Website

on:
  workflow_call:
    inputs:
      tag_name:
        type: string
        required: true
      fetch_depth:
        type: number
        default: 0
      build_type:
        type: string
        default: Release
      upload_artifact:
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build-web.yml
    with:
      fetch_depth: ${{ inputs.fetch_depth }}
      build_type: ${{ inputs.build_type }}
      upload_artifact: ${{ inputs.upload_artifact }}

  publish:
    name: Package and Upload Web Bundle
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Download Web Artifact
        uses: actions/download-artifact@v4
        with:
          name: multigauge-web
          path: web-artifact

      - name: Package Web Bundle into a ZIP
        run: |
          Compress-Archive -Path "web-artifact/*" -DestinationPath "ports-web-dist.zip" -Force

      - name: Upload Web WASM Zip to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          files: ports-web-dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
