name: Deploy Firmware

on:
  workflow_call:
    inputs:
      tag_name:
        type: string
        required: true
      fetch_depth:
        type: number
        default: 1
      upload_artifact:
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build-firmware.yml
    with:
      fetch_depth: ${{ inputs.fetch_depth }}
      upload_artifact: ${{ inputs.upload_artifact }}

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Firmware Artifact
        uses: actions/download-artifact@v4
        with:
          name: multigauge-firmware
          path: firmware-artifact

      - name: Upload Firmware Bin to GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ inputs.tag_name }}
          files: firmware-artifact/firmware.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
